baseURL = "https://www.redwallanalytics.com"
languageCode = "en-gb"
title = "Redwall Analytics"
theme = "hugo-lithium-theme"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug"
    
#[social]
	#github  = "luceydav"
	#twitter  = "lucey_david"

[menu]
    [[menu.main]]
    name = "Redwall Analytics"
    url = "/about/"
    weight = 1
    
    [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 2
    url = "/contact/"
    
    [[menu.main]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/david-lucey-cfa-cpa-mba-msba"
    weight = 3
    
    [[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/lucey_david"
    weight = 4
    
    [[menu.main]]
    name = "GitHub"
    url = "https://github.com/luceydav"
    weight = 5
    
[params]
    description = ""

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "redwall.png"
    width = 50
    height = 50
    
    #[params.copyright]
    #prefix = ""
    #holder = "David Lucey"
    #startYear = "2018"
    #suffix = ""
    
    #[params.sidebar]
    #enable = true


